services:
  accounts:
    image: "dthunn/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - dthunn
  loans:
    image: "dthunn/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - dthunn
  cards:
    image: "dthunn/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - dthunn
networks:
  dthunn:
    driver: "bridge"